//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Windows.Markup.XmlnsDefinitionAttribute("urn:shemas-jetbrains-com:ui-application-icons-cykumew-themed-icons", "JetBrains.UI.ThemedIcons")]

namespace ReSharperPlugin.FluentValidation
{
	/// <summary>
	///	<para>
	///		<para>FluentValidationLogo Themed Icon generated identifiers:</para>
	///		<para>— <see cref="FluentValidationLogo"></see> identifier class, for use in attributes, XAML, and generic parameters;</para>
	///		<para>— <see cref="Id"></see> identifier object, as a field in the identifier class, for use where an <see cref="JetBrains.UI.Icons.IconId"></see> value is expected.</para>
	///		<para>
	///			<code>
	///              `~~~~`
	///              ;@@@@p
	///              `@@@@i
	///     _L        g@@@!       ;)
	///    {@@@6;     D@@@.    -2g@@Q-
	///   !@@@@@@gV~  e@@@  -J$@@@@@@R
	///     -rVQ@@@@g6R@@gi$@@@@gpJ,
	///         `=VQ@@@@@@@@gE+.
	///           ~fg@@@@@@@2;`
	///      `=2$@@@@gg@@@$@@@@QEr-
	///   -Ag@@@@@gV~ f@@g -J$@@@@@@D)
	///    %@@@@E~    A@@@`   -iQ@@@@~
	///     VA!       Q@@@,      ,V$_
	///               @@@@J
	///              ~@@@@A
	///              .LL+~:
	///</code>
	///		</para>
	///	</para>
	///</summary>
	///<remarks>
	///	<para>For details on Themed Icons and their use, see Remarks on the outer class.</para>
	///</remarks>
	///<example>
	///	<code>&lt;Image Source="{icons:ThemedIcon myres:PahodolThemedIconsThemedIcons+FluentValidationLogo}" /&gt;        &lt;!-- XAML --&gt;</code>
	///</example>
	///<example>
	///	<code>[Item(Name="Sample", Icon=typeof(PahodolThemedIconsThemedIcons.FluentValidationLogo))]        // C# Type attribute</code>
	///</example>
	///<example>
	///	<code>IconId iconid = PahodolThemedIconsThemedIcons.FluentValidationLogo.Id;        // IconId identifier object</code>
	///</example>
	///<example>
	///	<code>themediconmanager.GetIcon&lt;PahodolThemedIconsThemedIcons.FluentValidationLogo&gt;()        // Icon image for rendering</code>
	///</example>
	[global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsAttribute()]
	public sealed class FluentValidationLogo : global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsClass
	{

		/// <inheritdoc cref="FluentValidationLogo">identifier class</inheritdoc>
		public static global::JetBrains.UI.Icons.IconId Id = new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsId(typeof(FluentValidationLogo));

		/// <summary>Loads the image for Themed Icon FluentValidationLogo theme aspect Default.</summary>
		public global::JetBrains.Util.Icons.TiImage Load_Default()
		{
			return global::JetBrains.Util.Icons.TiImageConverter.FromTiSvg("<svg ti:v=\'1\' width=\'16\' height=\'16\' viewBox=\'0,0,16,16\' xmlns=\'http://www.w3.org" +
					"/2000/svg\' xmlns:ti=\'urn:schemas-jetbrains-com:tisvg\'><g><path d=\'M7.107652,0.68" +
					"633299999999942C6.7116609999999994,0.71502799999999844,6.728878,0.63468199999999" +
					"8,6.8895700000000009,1.7652649999999994C7.050262,2.9360209999999984,7.170781,4.3" +
					"650319999999994,7.2166929999999994,5.6046559999999985L7.251127,6.695065999999998" +
					"9L6.969916,6.5286349999999995C6.149239,6.0522979999999986,3.497821,4.19860099999" +
					"99983,2.791924,3.6132229999999996L2.516452,3.3779239999999984L2.321326,3.6074839" +
					"999999995C1.879423,4.123994,1.15057,5.3521399999999986,1.15057,5.5817C1.15057,5." +
					"6046559999999985,1.403086,5.7309139999999985,1.7129919999999999,5.85717199999999" +
					"85C3.566689,6.637675999999999,6.350104,7.9748629999999991,6.338626,8.08390399999" +
					"99986C6.3214090000000009,8.2216399999999989,3.537994,9.5817829999999979,2.103244" +
					",10.155683C1.121875,10.540195999999998,1.167787,10.448371999999999,1.535083,11.3" +
					"03483C1.72447,11.739647,2.0573319999999997,12.290591,2.384455,12.721015999999999" +
					"C2.4590620000000003,12.824317999999998,2.516452,12.789883999999999,3.37730200000" +
					"00002,12.135638C4.685794,11.14853,7.06174,9.5416099999999986,7.2166929999999994," +
					"9.5416099999999986C7.3199950000000005,9.5416099999999986,7.084696000000001,12.72" +
					"1015999999999,6.860875,14.270546C6.792007,14.781317,6.740356,15.206002999999999," +
					"6.7518340000000006,15.217481C6.8149630000000005,15.292088,7.847983000000001,15.3" +
					"32260999999999,8.375971,15.28061C9.1736919999999991,15.200263999999999,9.386035," +
					"15.148613,9.374557,15.045311C9.122041,13.105528999999999,8.972827,11.613389,8.92" +
					"11759999999991,10.402459999999998C8.886742,9.6563899999999983,8.892481,9.5301319" +
					"999999983,8.961349,9.570305C10.155061,10.276201999999998,12.008758,11.5617379999" +
					"99998,13.208209,12.508672999999998C13.454986,12.709537999999998,13.673068,12.870" +
					"23,13.690285,12.87023C13.764892,12.87023,14.384704,11.842948999999999,14.614264," +
					"11.326438999999999C14.993038,10.482806,15.03895,10.574629999999999,14.00593,10.1" +
					"49943999999998C13.041778,9.759692,10.941304,8.7783229999999985,10.166539,8.35363" +
					"69999999991C9.810721,8.16425,9.707419,8.0781649999999985,9.764809,8.037992C10.25" +
					"2623999999999,7.7108689999999989,14.752,5.6390899999999995,14.98156,5.6390899999" +
					"999995C15.084862,5.6390899999999995,15.03895,5.5013539999999992,14.7577389999999" +
					"99,4.9676269999999985C14.488006,4.4625949999999985,13.873933,3.5500939999999996," +
					"13.701763,3.4123579999999993C13.638634,3.3607069999999997,13.54681,3.41235799999" +
					"99993,13.254121,3.6476569999999988C12.525268,4.250252,10.080454,5.966213,9.10482" +
					"39999999989,6.5573299999999985L8.881003,6.6950659999999989L8.9154369999999989,5." +
					"6620459999999984C8.95561,4.542940999999999,9.07039,3.2287099999999995,9.24256,1." +
					"8800449999999991C9.305689,1.4037079999999982,9.35734,0.97902199999999873,9.35734" +
					",0.92737099999999906C9.35734,0.85276399999999875,9.265516,0.8125909999999994,8.9" +
					"95783,0.76667899999999811C8.571097,0.69207199999999958,7.5782500000000006,0.6518" +
					"9899999999845,7.107652,0.68633299999999942ZM7.107652,0.68633299999999942\' fill=\'" +
					"#FF0000\'/></g></svg>");		}
		/// <summary>Returns the set of theme images for Themed Icon FluentValidationLogo.</summary>
		public override global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] GetThemeImages()
		{
			return new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage[] {
					new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.ThemedIconThemeImage("Default", new global::JetBrains.Application.Icons.CompiledIconsCs.CompiledIconCsIdOwner.LoadImageDelegate(this.Load_Default))};
		}
	}
}
